# name,repo uri,branch[,commit #comment]
# Base Software
poky,https://git.yoctoproject.org/poky,yocto-5.0.18,6473f88150795c2c238df176779fcc3e70027f95 # updated 2026-06-11
meta-openembedded,https://github.com/openembedded/meta-openembedded.git,scarthgap,d8cc4e44001c7257273d290ce8c4496e93d32841 # updated 2026-06-11
meta-virtualization,https://git.yoctoproject.org/meta-virtualization.git,scarthgap,9d0007a369deb4a6346f5ab7a9e6d432a8ed14fe # updated 2026-06-11
meta-mender,https://github.com/mendersoftware/meta-mender.git,scarthgap-v2026.04,b199a24d1c6172aae7d28961277fcfc4fb913979 # updated 2026-06-11
meta-mender-community,https://github.com/mendersoftware/meta-mender-community.git,scarthgap,6310a01a96f9f60715e136840b60d03e4ebd6b7c #pin To avoid using meta-lts-mixins with u-boot.
meta-terminal-system,https://github.com/aptpod/meta-terminal-system.git,3.3.0-scarthgap
# Machine(BSP)
meta-raspberrypi,https://github.com/agherzan/meta-raspberrypi.git,scarthgap,167703d5618498bb7feeaedf18e61be7a8246d1b # updated 2026-06-11
meta-edgeplant,https://github.com/aptpod/meta-edgeplant.git,2.3.0-scarthgap
# EOF
