# name,repo uri,branch[,commit #comment]
# Base Software
poky,https://git.yoctoproject.org/git/poky,scarthgap-5.0.5,5c705abecc00c8fc52af9a11b16d959e020c5327 # updated 2024-12-18
meta-openembedded,https://github.com/openembedded/meta-openembedded.git,scarthgap,3c293e14492f01e22a64004e2330fb620c27578a # updated 2025-01-07
meta-virtualization,https://git.yoctoproject.org/meta-virtualization.git,scarthgap,450941a1b6df96285691e8c23d4f332d3c88a994 # updated 2024-12-18
meta-mender,https://github.com/mendersoftware/meta-mender.git,scarthgap-v2024.12,5fed29626f7ec39452588726c3a76116d0e7c533 # updated 2025-01-07
meta-mender-community,https://github.com/mendersoftware/meta-mender-community.git,scarthgap,cb5dd30c043efcd4fab501d0cf9a8670031ab8df # updated 2024-12-18
meta-terminal-system,https://github.com/aptpod/meta-terminal-system.git,3.2.4-scarthgap
# Machine(BSP)
meta-raspberrypi,https://github.com/agherzan/meta-raspberrypi.git,scarthgap,6df7e028a2b7b2d8cab0745dc0ed2eebc3742a17 # updated 2024-11-12
meta-edgeplant,https://github.com/aptpod/meta-edgeplant.git,2.2.1-scarthgap
# EOF
