#
# container
#
## target arch
TS_TARGET_GOOS="linux"
TS_TARGET_GOARCH="amd64"
TS_TARGET_DEB_ARCH="amd64"
## device connector
TS_DISTRO_NAME_DEVICE_CONNECTOR="ubuntu"
TS_DISTRO_VERSION_DEVICE_CONNECTOR="24.04"
TS_DISTRO_CODENAME_DEVICE_CONNECTOR="noble"
TS_BASE_IMAGE_DEVICE_CONNECTOR="${TS_DISTRO_NAME_DEVICE_CONNECTOR}:${TS_DISTRO_VERSION_DEVICE_CONNECTOR}"
TS_IMAGE_NAME_DEVICE_CONNECTOR="device-connector-intdash/vtc1920"
TS_INSTALL_PACKAGES_DEVICE_CONNECTOR="gstreamer1.0-vaapi,intel-media-va-driver-non-free"

# EOF