# name,repo uri,branch[,commit #comment]
# Base Software
poky,https://git.yoctoproject.org/poky,yocto-5.0.18,6473f88150795c2c238df176779fcc3e70027f95 # updated 2026-06-11
meta-openembedded,https://github.com/openembedded/meta-openembedded.git,scarthgap,d8cc4e44001c7257273d290ce8c4496e93d32841 # updated 2026-06-11
meta-virtualization,https://git.yoctoproject.org/meta-virtualization.git,scarthgap,9d0007a369deb4a6346f5ab7a9e6d432a8ed14fe # updated 2026-06-11
meta-mender,https://github.com/mendersoftware/meta-mender.git,scarthgap-v2026.04,b199a24d1c6172aae7d28961277fcfc4fb913979 # updated 2026-06-11
meta-mender-community,https://github.com/mendersoftware/meta-mender-community.git,scarthgap,57dc30d45cc402458f177cbf57412401fb7b146e # updated 2026-06-11
meta-terminal-system,https://github.com/aptpod/meta-terminal-system.git,3.3.0-scarthgap
# Machine(BSP)
meta-intel,https://git.yoctoproject.org/meta-intel.git,scarthgap,5d153e35b4e752505efeae368f188fac5e31cf33 # updated 2026-03-24
# EOF
