# CVE Status
# Ingore the check for a given list of CVEs. If a CVE is found,
# then it is considered patched.

CVE_STATUS_GROUPS = "CVE_STATUS_NOT_USED"

CVE_STATUS_NOT_USED = " \
"
CVE_STATUS_NOT_USED[status] = "not-applicable-platform: Not used"

CVE_CHECK_REPORT_PATCHED="0"
