# name,repo uri,branch[,commit #comment]
# Base Software
poky,https://git.yoctoproject.org/poky,yocto-4.0.35,f89c178d4ee9415ee7417f92b70a93f1dc43ad64 # updated 2026-06-11
meta-openembedded,https://github.com/openembedded/meta-openembedded.git,kirkstone,ce8539c941f6fcbecaca4d16640ac105c0595589 # updated 2026-06-11
meta-virtualization,https://git.yoctoproject.org/meta-virtualization.git,kirkstone,92b6abcdfb6f12c4931247f0f29aaf5331984525 # updated 2026-06-11
meta-mender,https://github.com/mendersoftware/meta-mender.git,kirkstone-v2026.04,27b91e0876dda207c13f972e0aab82579468accf # updated 2026-06-11
meta-mender-community,https://github.com/mendersoftware/meta-mender-community.git,kirkstone,7288d1e1e97aab23aa796a8ecdb6c6306afa778c # updated 2026-06-11
meta-terminal-system,https://github.com/aptpod/meta-terminal-system.git,3.3.0-kirkstone
# Machine(BSP)
meta-tegra,https://github.com/OE4T/meta-tegra.git,kirkstone-l4t-r32.7.x,94e3db3146dc273ec1df463426c0fcaeacc51b5f # updated 2025-12-24
meta-edgeplant,https://github.com/aptpod/meta-edgeplant.git,2.2.0-kirkstone
# EOF