# name,repo uri,branch[,commit #comment]
# Base Software
poky,https://git.yoctoproject.org/poky,kirkstone-4.0.23,ec6c0246b933a8b0bfcca3f538160bb7b92a3f39 # updated 2024-12-18
meta-openembedded,https://github.com/openembedded/meta-openembedded.git,kirkstone,7b3fdcdfaab2fc964bbf9eec2cce4e03001fa8cf # updated 2024-12-18
meta-virtualization,https://git.yoctoproject.org/meta-virtualization.git,kirkstone,a055d7dcafc58855081a5eac9a46b93b9b51012b # updated 2024-12-18
meta-mender,https://github.com/mendersoftware/meta-mender.git,kirkstone-v2024.12,a237b2e6687903c2bbfe736339e840eef839c800 # updated 2025-01-07
meta-mender-community,https://github.com/mendersoftware/meta-mender-community.git,kirkstone,1068f3427a9c6956cefca2f920ce29ed52256dee # updated 2024-11-05
meta-terminal-system,https://github.com/aptpod/meta-terminal-system.git,3.2.9-kirkstone
# Machine(BSP)
meta-tegra,https://github.com/OE4T/meta-tegra.git,kirkstone-l4t-r32.7.x,fd5f9971d6fb07130da3b3bf0e8f04745d5ceed8 # updated 2024-12-18
meta-edgeplant,https://github.com/aptpod/meta-edgeplant.git,2.2.0-kirkstone
# EOF